server:
  port: 8086
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/acme

  datasource:
    url: jdbc:postgresql://demoeastus2.postgres.database.azure.com:5432/postgres?sslmode=require
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: *
    health:
      show-details: always
  info:
    env:
      enabled: true
